# Generated by Django 3.2.8 on 2021-12-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('age', models.IntegerField(db_column='age')),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('date', models.DateField(db_column='date')),
                ('color', models.CharField(db_column='color', max_length=20)),
                ('type', models.CharField(db_column='type', max_length=20)),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
