# Generated by Django 3.2.8 on 2021-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=20)),
                ('age', models.IntegerField(db_column='age')),
                ('hobby', models.CharField(db_column='hobby', max_length=20)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
